language: node_js
node_js:
  - 12
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
stages:
  - check
  - build
before_install:
  - npm install -g yarn
jobs:
  include:
    - stage: check
      script: yarn run check
    - stage: build
      script: CI=false PUBLIC_URL=https://ushitora-anqou.github.io/damjiro/ yarn build
deploy:
  provider: pages
  token: $GITHUB_TOKEN
  edge: true
  local_dir: build/
