language: node_js
node_js:
    - 12
branches:
    only:
        - master
before_install:
  - npm install -g yarn
script:
    - CI=false PUBLIC_URL=https://ushitora-anqou.github.io/damjiro/ yarn build
deploy:
    provider: pages:git
    token: $GITHUB_TOKEN
    edge: true
    local_dir: build/
