language: node_js
node_js:
  - 12
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
  - npm install -g yarn
script:
  - yarn run check
  - CI=false PUBLIC_URL=https://ushitora-anqou.github.io/damjiro/ yarn build
deploy:
  provider: pages
  strategy: git
  token: $GITHUB_TOKEN
  edge: true
  local_dir: build/